# Generated by Django 5.2.8 on 2025-11-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_add_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
