import random
import string
from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from django.utils import timezone

class Command(BaseCommand):
    help = 'Seed development DB with 10 users, random friendships, and posts'

    def handle(self, *args, **options):
        User = get_user_model()
        from posts.models import Post

        created = []
        # Create 10 users
        for i in range(10):
            email = f'user{i+1}@example.com'
            if User.objects.filter(email=email).exists():
                self.stdout.write(self.style.WARNING(f'User already exists: {email}'))
                user = User.objects.get(email=email)
                created.append(user)
                continue

            name = f'User {i+1} ' + ''.join(random.choices(string.ascii_lowercase, k=5))
            user = User.objects.create_user(email=email, name=name, password='password123')
            created.append(user)
            self.stdout.write(self.style.SUCCESS(f'Created user: {email}'))

        # Create random friendships
        for user in created:
            others = [u for u in created if u != user]
            if not others:
                continue
            num = random.randint(1, min(3, len(others)))
            friends = random.sample(others, k=num)
            for f in friends:
                user.friends.add(f)
                f.friends.add(user)
            self.stdout.write(f'Added {len(friends)} friends for {user.email}')

        # Sample texts
        sample_texts = [
            'What a beautiful day!',
            'Trying out this new app.',
            'Hello world — posting from seed script.',
            'Coffee and coding.',
            'Sharing a short thought.',
            'Had a productive day!',
            'Anyone up for a chat?',
            'Exploring the features here.',
            'This is an autogenerated post.',
            'Testing posts creation.'
        ]

        # Create 1-3 posts per user
        total_posts = 0
        for user in created:
            cnt = random.randint(1, 3)
            for _ in range(cnt):
                text = random.choice(sample_texts) + f' (by {user.name})'
                p = Post.objects.create(author=user, text=text)
                total_posts += 1
        self.stdout.write(self.style.SUCCESS(f'Created {total_posts} posts'))
        self.stdout.write(self.style.SUCCESS('Seeding complete'))
